name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Deploy Application
        shell: powershell
        run: |
          robocopy '.' 'C:\CadDo\FutureETL\' /E /XD '.git' '.github' '.venv' '.pytest_cache'
          $robocopyExitCode = $LASTEXITCODE

          if ($robocopyExitCode -ge 8) {
            Write-Host "Robocopy failed with exit code $robocopyExitCode"
            exit 1  # Fail the step
          } else {
            Write-Host "Robocopy completed with exit code $robocopyExitCode"
            exit 0  # Succeed the step
          }
