name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Deploy Application
        run: |
          robocopy '.' 'C:\CadDo\FutureETL\' /E /XD '.git' '.github' '.venv' '.pytest_cache'
          if ($LASTEXITCODE -gt 8) { exit 1 }
        shell: powershell
